### ISSUE TITLE
illegal timezone

### ISSUE THREAD

**Issue by goerdi** [dorchain/dcfshm#3]
Hi ! 
i always get

    1003017: 0xc0 11000000 59 -> 1 1649766000 0
    New minute detected after 59 bits
    Illegal time zone 1 1
    -92: 0xc0 11000000 01 -> 1 1649766001 0
    its running on Ubuntu 20.04... i have it on another device running and there it runs fine....

on this device also it shows on startup in -d mode
pivot year set to 2022
on the device where it runs fine it shows 
pivot year set to 2021

Ciao Gerd

**Comment by dorchain** [comment]
From the comments in the source:
```
 * 17 - 18	Z1,Z2 - time zone
 *		 0  0 illegal
 *		 0  1 MEZ  (MET)
 *		 1  0 MESZ (MED, MET DST)
 *		 1  1 illegal

```

So this looks like mis-received bits.

The pivot year in the year when it was compiled. As DCF77 only transmits the last two digits of the year, it will be used to guess the century.

I know that I have to rethink this strategy in 99 years ;)

**Comment by goerdi** [comment]
Hmm always a bit missing...  ? i live 30 km away from sender and they are both the same receivers... only in 2 different rooms...

**Comment by goerdi** [comment]
OK it works.... it seems on this machine i have to deal with -b 4800 option....
